# Generated by Django 2.2.16 on 2022-03-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_code',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(max_length=100, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('anon', 'anonimus'), ('admin', 'admin'), ('moderator', 'moderator'), ('user', 'user')], max_length=10, null=True, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=20, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
