# Generated by Django 2.2.16 on 2022-03-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220306_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('anon', 'anonimous'), ('admin', 'admin'), ('moderator', 'moderator'), ('user', 'user')], max_length=10, null=True, verbose_name='Роль'),
        ),
    ]
