# Generated by Django 2.2.16 on 2022-03-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220305_1925'),
        ('reviews', '0004_auto_20220305_2059'),
    ]

    operations = [
    ]
