# Generated by Django 2.2.16 on 2022-03-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_merge_20220305_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desctiption',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание'),
        ),
    ]
