# Generated by Django 2.2.16 on 2022-03-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_merge_20220305_1710'),
        ('reviews', '0008_genre_description'),
    ]

    operations = [
    ]
