# Generated by Django 2.2.16 on 2022-03-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_genre_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
