# Generated by Django 2.2.16 on 2022-03-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20220309_1703'),
        ('reviews', '0017_auto_20220309_2051'),
    ]

    operations = [
    ]
