# Generated by Django 2.2.16 on 2022-03-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_auto_20220310_0012'),
        ('reviews', '0018_merge_20220309_1953'),
    ]

    operations = [
    ]
