# Generated by Django 2.2.16 on 2022-03-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_auto_20220310_1632'),
        ('reviews', '0020_auto_20220310_1920'),
    ]

    operations = [
    ]
